### ISSUE TITLE
Question: what would make your prompt non-asynchronous in VSCode terminal?

### ISSUE THREAD

**Issue by borekb** [agkozak/agkozak-zsh-prompt#10]
I usually use ConEmu as my terminal on Windows but wanted to try VSCode with very similar settings, basically, this in `settings.json`:

```
    "terminal.integrated.shell.windows": "c:\\Users\\borek\\Programs\\ConEmu\\conemu\\conemu-msys2-64.exe",
    "terminal.integrated.env.windows": {
        "CHERE_INVOKING": "1",
        "MSYSTEM": "MINGW64",
        "MSYS2_PATH_TYPE": "inherit",
    },
    "terminal.integrated.shellArgs.windows": [
        "zsh",
        "-l",
        "-i",
    ],
```

What is strange is that in VSCode's terminal, the prompt waits for the Git info to be fetched, only then appears. As if there was no asynchronicity.

This might be an issue with VSCode itself but before I report there, I wanted to ask you, @agkozak, if you have any clue why that would be the case. It would be much appreciated, thanks!

**Comment by agkozak** [comment]
Interesting. The prompt works perfectly and asynchronously in MSYS2 in VSCode (just using` zsh.exe`).

To be honest, I can't get your configuration as given above to work at all in VSCode (and of course I am adjusting the path to `conemu-msys2-64.exe`). I just get an error message. Is that program even supposed to be invoked outside of  ConEmu itself? I believe that you've got it working; I just can't seem to get there myself. Do you know of any guides to integrating ConEmu as an integrated terminal in VSCode? Thanks.

**Comment by borekb** [comment]
I'll do some more experiments later today but:

> Is that program even supposed to be invoked outside of ConEmu itself?

Yes, I believe `conemu-msys2-64.exe` can be used outside of ConEmu. I think it's just a normal binary that provides POSIX environment for whatever is executing "through" it.

> Do you know of any guides to integrating ConEmu as an integrated terminal in VSCode?

Both ConEmu and VSCode's terminal are terminal emulators, so at the same level. They run whichever binary they are instructed to, and I believe running `zsh.exe` in VSCode directly is the same as creating a ConEmu task that will just run `zhs.exe -i -l` wihout the Cygwin/MSYS2 connector.

I tried to run without the Cygwin/MSYS2 connector in ConEmu but hit too many issues, for example, colors were sometimes not working properly, npm and Yarn were doing strange path manipulations (adding "C:\..." to Linux paths), etc.

In VSCode, if I remember correctly, running `zsh.exe` directly without the connector had a huge performance impact, making it virtually unusable, but I need to confirm that when I get to a Windows computer.

**Comment by agkozak** [comment]
I can see why you want to use it.

`conemu-msys2-64.exe` seems to work perfectly for me inside ConEmu, but if I try to launch it from the File Explorer, I get an error message saying that it can't find `msys-2.0.dll`. I'll keep working at this: I'm keen to reproduce your environment and fix things.

**Comment by agkozak** [comment]
While I work on trying to get ConEmu to work properly, why don't you try typing

    print $AGKOZAK_ASYNC_METHOD

into your integrated terminal and see what it says.

**Comment by borekb** [comment]
Strange, I'm on a Windows machine now, but a different one than in the morning. All works fine in VSCode, even with the MSYS2 Connector. Hm....

By the way, my environment is set up like this: [Zsh on Windows via MSYS2](https://medium.com/@borekb/zsh-via-msys2-on-windows-3964a943b1ce). With PATH correctly updated, I can open Command Prompt and execute this there:

```
set CHERE_INVOKING=1 & set MSYSTEM=MINGW64 & set MSYS2_PATH_TYPE=inherit & C:\path\to\conemu-msys2-64.exe C:\msys64\usr\bin\zsh.exe --login -i
```

and get a zsh shell inside Windows console. It is quite amazing :)

**Comment by borekb** [comment]
After some more testing, on my desktop PC:

## zsh in VSCode via ConEmu Connector

VSCode configuration:

```
    "terminal.integrated.shell.windows": "c:\\path\\to\\ConEmu\\conemu\\conemu-msys2-64.exe",
    "terminal.integrated.env.windows": {
        "CHERE_INVOKING": "1",
        "MSYSTEM": "MINGW64",
        "MSYS2_PATH_TYPE": "inherit",
    },
    "terminal.integrated.shellArgs.windows": [
        "zsh",
        "-l",
        "-i",
    ],

```

All works fine: prompt is there, is asynchronous, Git info uses gray color.

![image](https://user-images.githubusercontent.com/101152/43985079-fd0fac9c-9d04-11e8-86e5-adfabd30f81e.png)

## zsh in VSCode without connector

Settings:

```
    "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\zsh.exe",
    "terminal.integrated.env.windows": {
        "CHERE_INVOKING": "1",
        "MSYSTEM": "MINGW64",
        "MSYS2_PATH_TYPE": "inherit",
    },
    "terminal.integrated.shellArgs.windows": [
        "-l",
        "-i",
    ],
```

All seems to be fine except Git info color – it's white for some reason.

I don't have any performance issues this time.

![image](https://user-images.githubusercontent.com/101152/43985129-4d877362-9d05-11e8-80ff-b64e04e02aae.png)

## zsh in Command Prompt

Open command prompt and type this there:

```
set CHERE_INVOKING=1 & set MSYSTEM=MINGW64 & set MSYS2_PATH_TYPE=inherit & C:\path\to\conemu-msys2-64.exe C:\msys64\usr\bin\zsh.exe --login -i
```

Partly working, for example, my .zshrc is loaded, I can invoke my aliases, get colored output, etc. But the Git info is missing, which is most likely due to the broken path. Maybe I'm not executing this right (I'm not sure how to properly set environment variables for the nested shell).

![image](https://user-images.githubusercontent.com/101152/43985191-c28a391a-9d05-11e8-82f8-e3ca99afb54c.png)

**Comment by borekb** [comment]
I'm now on my Windows laptop from which I've originally reported the issue with non-asynchronous prompt, and I can't reproduce it. All behaves as expected, and I observe exactly the same as in the previous comment. Maybe it was some temporary glitch.

**Comment by agkozak** [comment]
I'm glad to hear it's all working correctly.

I so wish I could get ConEmu to work as well! What you're describing sounds great, but both on my desktop and on my wife's laptop I have trouble getting the connector (`conemu-msys2-64.exe`) to find `msys-2.0.dll`. If I run the commands you list from the `C:\tools\msys64\usr\bin` directory where `msys-2.0.dll` resides, then it all works, but only barely -- I get all sorts of undesirable effects in my terminal. If I just run everything inside `ConEmu.exe` itself, it works better, but even then, `tmux` isn't usable -- the screen is corrupted from the very start.

I see so many people report good things about using ConEmu, so it must just be me, but I honestly don't know what to do next. I'm keen on trying any terminal or environment that people are likely to use my scripts with, so I'll keep trying, but...it's frustrating.

**Comment by borekb** [comment]
Strange. I assume `C:\tools\msys64\usr\bin` is in your path, right? BTW, I'd had good experience asking questions in [this Gitter room](https://gitter.im/msys2/msys2).

**Comment by agkozak** [comment]
> Strange. I assume C:\tools\msys64\usr\bin is in your path, right?

Yes, that helps! 👍

All the same, in a `cmd.exe` box I get a lot of unprocessed escape codes:

![image](https://user-images.githubusercontent.com/7599319/44071222-b0d383e6-9f3c-11e8-841c-bb7ed968e3dc.png)

There seem to be many fewer if I run `bash.exe` instead of `zsh.exe`. Either way, I get a stackdump every time I exit the shell.

I'll check out that Gitter room -- thanks!

**Comment by borekb** [comment]
Which version of Windows are you on? Console only got better in a recent Win10 updates.

**Comment by agkozak** [comment]
This is the latest version of Windows 10. I'm pretty sure my problem has everything to do with ConEmu, as I am able to launch WSL from cmd.exe and get all the colors I want:

![image](https://user-images.githubusercontent.com/7599319/44096431-17407eba-9f90-11e8-887f-6cff5f601e6f.png)
