### ISSUE TITLE
git status is not getting updated when using usr1 async mode.

### ISSUE THREAD

**Issue by moonrumble** [agkozak/agkozak-zsh-prompt#12]
I am getting following error using cygwin and git prompt is not getting updated. If I delete the tmp file, it works as expected. 

_agkozak_usr1_async_worker:2: file exists: /tmp/agkozak_zsh_prompt_1340

Thanks

**Comment by agkozak** [comment]
Yes, I can see how that could happen. Cygwin and MSYS2 temp directories do not seem to get cleaned up very often.

I'm about to release a new version of the prompt that uses a completely different method for producing the asynchronous Git status. Would you like to try it? Just go to the directory where the `agkozak-zsh-prompt.plugin.zsh` script is stored and run

    git checkout develop
    git pull

and start up a fresh shell. That should put you on the `develop` branch, with all the latest updates. I'll release the latest version  in a few days, once I've updated the documentation, but do tell me if you run into any problems.

**Comment by moonrumble** [comment]
Unfortuatenly, I am still getting the same error.

**Comment by moonrumble** [comment]
Thank You for the quick response. I have set it to be usr1 based on the documentation so it says.

> usr1

After I removed forced configuraton, it is 

> subst-async

 but my prompt is very slow compare to pure prompt using async.zsh.

When I forced async method to be zsh-async, my prompt stops working. I am seeing the same behavior in master branch as well.

**Comment by agkozak** [comment]
I don't think you'll be able to get pure with `async.zsh` to work in Cygwin, as it requires the `zpty` module, which loads and then crashes in Cygwin.

As I've been fiddling about with the new method of delivering the Git status, I have also found it to be somewhat unsatisfactory in Cygwin and MSYS2. Until I resolve its issues, I'd encourage you to use the `master` branch again, and just run

    rm /tmp/agkozak_zsh_prompt*

once to get rid of all the temporary files. I'll get all of this sorted out soon. Thanks so much for your thoughtful comments -- you're really helping to make this prompt better for everyone.

**Comment by moonrumble** [comment]
pure is working with `async.zsh`. Problem is I am not able to kill the zsh. Window will stay open until I run `tskill zsh`. I am sure you are awayre of the issue and related discussion on `async` and `pure` git repo.

**Comment by agkozak** [comment]
@moonrumble  It's interesting that you got the "file exists" error message. I've never actually seen that happen with my prompt. Could you check to see if you've got the `noclobber` option set in your shell? You can just type `setopt` and it should list all of the options that are enabled.

**Comment by agkozak** [comment]
I've just pushed to the `develop` branch a version of the prompt that will use `usr1` by default on Cygwin and that has a workaround for the `noclobber` setting. Give it a try -- I think it should fix your original problem.

**Comment by moonrumble** [comment]
you were correct. I had `noclobber` set. After updating develop branch, now prompt is working as expected. 

How are you measuring performance? I want to help testing with few other prompts. It might be my imagination but it feels little slower compare to `pure`. I have no data to back my claim but I am happy to run some test.

**Comment by agkozak** [comment]
I just played around with pure in Cygwin, and you're right -- it does seem a bit faster in rendering the main part of the prompt (although anyone reading this should note that your shell will hang when you try to exit).

I'll try to get around to writing a benchmark for the two soon. In the meantime, I noticed one major difference between my shell and pure is that mine gives you your vi mode in the left prompt out of the box (I seem to remember there's a nice way of tweaking pure to do that, too). Up till now, I've just used command substitution in the prompt to achieve that, but I just replaced it with a ZSH prompt ternary statement and eliminated the subshell. You might notice a slight performance improvement -- try the `develop` branch for now.

**Comment by agkozak** [comment]
Actually, it looks as if pure has made a vi status indicator a builtin feature since I last checked up on it. Very nice.

**Comment by agkozak** [comment]
You can also speed up my prompt a bit by running AGKOZAK_NAMED_DIRS=0 at the command line or in your `.zshrc`. The difference is that it won't display ZSH named (hashed) directories as being special anymore, but it does avoid two subshells, which are costly in terms of performance in Windows.

**Comment by agkozak** [comment]
It may not even be necessary to do `AGKOZAK_NAMED_DIRS=0`, as I've just removed a subshell by changing

    zsh_pwd=$(print -Pn '%~')

to

    print -v zsh_pwd -Pn '%~'

**Comment by moonrumble** [comment]
Now it feels snappier then before. Thanks

**Comment by agkozak** [comment]
Thanks. I think today you'll find it to be even snappier -- I've eliminated another subshell. As I'm sure you know, in shell scripting, the most classic way of assigning the output of a function to a variable is `var=$( print 'something')`, but in Cygwin, the subshell produced by command substitution is very slow. Now, whenever I can, I'm replacing that sort of construct with

    print -z 'something'
    read -rz var

It looks terrible, but it's much faster.

I need to look very closely at `pure`'s code, but I think you can get the sort of benchmarking you want by sourcing

    typeset -Fg SECONDS start

    benchmark_start() {
      start=$SECONDS
    }

    precmd_functions=(benchmark_start $precmd_functions)

    zle-line-init() {
      PREDISPLAY="[$(( SECONDS - start ))] "
    }

(Derived from https://unix.stackexchange.com/questions/295679/how-can-i-profile-prompt-rendering-time-in-zsh). That will give you the time it takes for the left prompt to be rendered. `pure` is still faster, but my prompt won't lock up Cygwin!

Rest assured that I will continue to knock milliseconds off my prompt's execution time. Since we've solved your original problem, I'm going to close this issue, but do feel free to reach out to me with other issues. Many thanks for inspiring me to make it better!

**Comment by moonrumble** [comment]
Thank You.
