### ISSUE TITLE
Local/remote sessions

### ISSUE THREAD

**Issue by Defman21** [agkozak/agkozak-zsh-prompt#14]
Could you please explain how I can make this prompt work on a remote server? I've tried to Google something about zsh remote sessions but didn't find anything useful.

**Comment by agkozak** [comment]
I'd be happy to help. Have you installed agkozak-zsh-prompt on the remote server yet? If so, how have you installed it and how are you sourcing it? Are you using a framework like oh-my-zsh or any other?

**Comment by Defman21** [comment]
Oh I have to install it on the server as well? Thanks, will try..

**Comment by Defman21** [comment]
It works. Thanks for your help!
