### ISSUE TITLE
Hide user and hostname

### ISSUE THREAD

**Issue by SultanSGillani** [agkozak/agkozak-zsh-prompt#16]

**Comment by SultanSGillani** [comment]
Is there any possible way to completely hide user and hostname regardless of session type?

**Comment by agkozak** [comment]
You can do that. There's no simple setting for it, but you can do almost anything by using `$AGKOZAK_CUSTOM_PROMPT`. The default behavior of the left prompt can be represented thus:

    AGKOZAK_CUSTOM_PROMPT='%(?..%B%F{red}(%?%)%f%b )'
    AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{green})%n%1v%(!.%b%s.%f%b) '
    AGKOZAK_CUSTOM_PROMPT+=$'%B%F{blue}%2v%f%b\n'
    AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '

The second line is where the username (`%n`) and hostname (`%1v`) are displayed, so you can just remove the second line, and put it in your `.zshrc`:

    AGKOZAK_CUSTOM_PROMPT='%(?..%B%F{red}(%?%)%f%b )'
    AGKOZAK_CUSTOM_PROMPT+=$'%B%F{blue}%2v%f%b\n'
    AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '

That should work. Give it a try.

Using the `$AGKOZAK_CUSTOM_PROMPT` and `$AGKOZAK_CUSTOM_RPROMPT` can mess up the behavior of some of the simpler settings of agkozak-zsh-prompt, though. You can read about it in the "Customization" section of the documentation (see especially "Advanced Customization"). If you're trying to make several customizations, let me know what they are and I'll give you the code.

**Comment by SultanSGillani** [comment]
Thanks. Per your README I’m just using the example of
 AGKOZAK_PROMPT_CHAR=( ❯ ❯ ❮ )
AGKOZAK_COLORS_PROMPT_CHAR='magenta'

Without any major customizations. Thanks!!

**Comment by agkozak** [comment]
Great. Try copying and pasting this:

    AGKOZAK_CUSTOM_PROMPT='%(?..%B%F{red}(%?%)%f%b )'
    AGKOZAK_CUSTOM_PROMPT+=$'%B%F{blue}%2v%f%b\n'
    AGKOZAK_CUSTOM_PROMPT+='%F{magenta}%(4V.❮.❯)%f '

**Comment by SultanSGillani** [comment]
Thanks that works!!
