### ISSUE TITLE
How to remove spaces around the git tag?

### ISSUE THREAD

**Issue by zhuxiaoxi** [agkozak/agkozak-zsh-prompt#17]
I want to remove this space, just like the left side. thanks

<img width="964" alt="2019-02-20 22 04 52" src="https://user-images.githubusercontent.com/2098464/53097360-40af3b80-355c-11e9-8ec2-8953fe18d8b6.png">

```
    AGKOZAK_CUSTOM_PROMPT='%(4V.%F{magenta}:%f.%F{cyan}%#%f) ' # Prompt¬
    AGKOZAK_CUSTOM_RPROMPT='%(?..%B%F{red}(%?%)%f%b )'         # Exit Code¬
    AGKOZAK_CUSTOM_RPROMPT+=$'%B%F{blue}%2v%f%b'               # Path¬
    AGKOZAK_CUSTOM_RPROMPT+='%(3V.%K{yellow}%3v%k.)'           # Git¬
```

**Comment by agkozak** [comment]
I've just implemented a new setting that should help you. Go to wherever you have agkozak-zsh-prompt stored and run

    git pull
    git checkout develop
    zsh

Then try

    AGKOZAK_BRANCH_STATUS_SEPARATOR=''

That should make the space disappear. Let me know if it works -- I can release it on the `master` branch soon. You may put it in your .zshrc along with the custom prompt lines you already have.

**Background:** The ideal way to do this would be to be able to include or omit spaces in `$AGKOZAK_CUSTOM_PROMPT`/`$AGKOZAK_CUSTOM_RPROMPT`, but I originally designed the function `_agkozak_branch_status` to output a preceding space, and I don't want to break everyone else's custom prompts by changing it now. For now, I think this sort of workaround is the best thing.

**Comment by zhuxiaoxi** [comment]
it works.
I think that removing the space completely in BRANCH_STATUS, adding spaces in PROMPT, more user-friendly. Or add an option to let the user choose whether to remove all spaces.


There is still a space on the right side.
![](https://user-images.githubusercontent.com/2098464/53217462-05fbef00-3693-11e9-8c99-2ad279ead6c7.jpg)

**Comment by agkozak** [comment]
The space on the right side is something ZSH itself does, but you can adjust it with

    ZLE_RPROMPT_INDENT=0

See if that looks better in your terminal.

**Comment by zhuxiaoxi** [comment]
If you do this, the space on the left prompt will also disappear.
<img width="217" alt="2019-02-22 11 47 24" src="https://user-images.githubusercontent.com/2098464/53218595-b4a22e80-3697-11e9-91da-3e99dded3484.png">

**Comment by zhuxiaoxi** [comment]
thank. I solved it
```
AGKOZAK_CUSTOM_PROMPT='%(4V.%F{magenta}:%f.%F{cyan}%#%f)˽˽' # Prompt
```
