### ISSUE TITLE
Is is possible to add Powerline Font character in prompt?

### ISSUE THREAD

**Issue by WayneChang65** [agkozak/agkozak-zsh-prompt#18]
I'd like to add [Powerline fonts](https://github.com/powerline/fonts) characters in prompt. (as a separator by AGKOZAK_BRANCH_STATUS_SEPARATOR)
like this below
![image](https://user-images.githubusercontent.com/33888917/56950306-c1e00b80-6b67-11e9-93bd-5a9f98295d1e.png)

If I copy & paste it directly, it becomes that below and fail.
![image](https://user-images.githubusercontent.com/33888917/56950580-682c1100-6b68-11e9-9552-8143a464cfdd.png)

Is is possible now? Thanks.

**Comment by agkozak** [comment]
I'm pretty sure this is a problem related to the terminal you're using. What operating system and terminal are you using?

**Comment by WayneChang65** [comment]
I use [PieTTY](https://sites.google.com/view/pietty-project) for the terminal on Windows 7.
This prompt theme [shayan-zsh-theme](https://github.com/shayanh/shayan-zsh-theme) shows the Unicode character correctly in same PieTTY.
![image](https://user-images.githubusercontent.com/33888917/57053345-f961cb80-6cbf-11e9-9bee-22862f7f4415.png)

I check shayan.zsh-theme out and try to assign "\ue0a0 " to AGKOZAK_BRANCH_STATUS_SEPARATOR as shown below.
![image](https://user-images.githubusercontent.com/33888917/57053251-632da580-6cbf-11e9-9d32-8c71a9b3fe10.png)
Unfortunately... it shows  
![image](https://user-images.githubusercontent.com/33888917/57053312-b9024d80-6cbf-11e9-8558-5d8d4e7d21c4.png)
Any ideas?

**Comment by agkozak** [comment]
Thanks. That's a very helpful explanation of what looks like a genuine problem! I get the same problem in mintty, in fact.

All right. Give me a couple of days and I'll try to produce a fix.

**Comment by WayneChang65** [comment]
Thanks for the great work. agkozak-zsh-prompt is really impressive and flexible for customization. I love it. :)

**Comment by agkozak** [comment]
[Here's the source of the problem.](https://www.zsh.org/mla/users/2005/msg00863.html) Using "expandos" such as `%1v` in the prompt strings to refer to `psvar[1]`, etc. does not necessarily display Powerline symbols. Frequently ZSH treats them as potentially dangerous escape sequences; hence the literal treatment of `\ue0a0` in your example.

I've noticed that the problem occurs on Windows (with MSYS2 and Cygwin) and on FreeBSD, but not on Ubuntu or CloudLinux -- I'll be curious to see why the differences occur.

We can work around this problem by using `${psvar[1]}`, etc. instead of `%1v`, etc. It will take me a little while to decide what to do with the core code of the prompt, but in the meantime you can replace the settings you showed me above with

    AGKOZAK_BLANK_LINES=1
    AGKOZAK_CUSTOM_SYMBOLS=( '⇣⇡' '⇣' '⇡' '+' 'x' '!' '>' '?' )
    AGKOZAK_BRANCH_STATUS_SEPARATOR=" \ue0a0 "

    AGKOZAK_CUSTOM_PROMPT='%(?..%B%F{red}(%?%)%f%b )'
    AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{cyan})%n%1v%(!.%b%s.%f%b) '
    AGKOZAK_CUSTOM_PROMPT+=$'%B%F{red}%2v%f%b'
    AGKOZAK_CUSTOM_PROMPT+=$'%(3V.%F{yellow}${psvar[3]}%f.)\n'
    AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '

    AGKOZAK_CUSTOM_RPROMPT=

How does that look?

And perhaps you can help me test out a new version of agkozak-zsh-prompt for Powerline fonts soon?

**Comment by WayneChang65** [comment]
Good morning.
I tried to modify my .zshrc as you mentioned below: 
![image](https://user-images.githubusercontent.com/33888917/57203191-91bdc000-6fe0-11e9-9aaf-410f9a3b195d.png)

And the result :
![image](https://user-images.githubusercontent.com/33888917/57203202-a5692680-6fe0-11e9-8eb9-3e552eb09880.png)

Hope it helps.

**Comment by agkozak** [comment]
Too bad.

I'll try to get a CentOS virtual machine up and running and see what's happening.

Many thanks for your feedback.

By the way, could you run

    locale

on your CentOS server and tell me what it says? Thanks.
.

**Comment by WayneChang65** [comment]
It shows OK by mintty on Cygwin. Wow~
![image](https://user-images.githubusercontent.com/33888917/57203536-8c15a980-6fe3-11e9-826d-5ef0b6354fbb.png)
![image](https://user-images.githubusercontent.com/33888917/57203547-9e8fe300-6fe3-11e9-8dce-da2ad97ea6f3.png)

By the way, locale says below:
1. CentOS Server
![image](https://user-images.githubusercontent.com/33888917/57203561-bff0cf00-6fe3-11e9-92df-5f815d7aafec.png)

2. Cygwin (on Windows 7)
![image](https://user-images.githubusercontent.com/33888917/57203619-3ee60780-6fe4-11e9-859e-ab0aaaa6b93a.png)

Difference between zh_TW and  en_US ?

**Comment by WayneChang65** [comment]
One more thing has to be mentioned is that it shows correct on cygwin by mintty and then I try it on VSCode. An exception-like message shows out as below:

![image](https://user-images.githubusercontent.com/33888917/57203889-3bec1680-6fe6-11e9-8ac4-50bcdfd6525c.png)

Any ideas?

**Comment by agkozak** [comment]
Could you try changing

    AGKOZAK_BRANCH_STATUS_SEPARATOR=" \ue0a0 "

to

    AGKOZAK_BRANCH_STATUS_SEPARATOR=$' \ue0a0 '

and see if that makes a difference?

I'll get back to you on the other points a little later.

**Comment by WayneChang65** [comment]
I change it as you said and it shows correctly !!!
![image](https://user-images.githubusercontent.com/33888917/57266433-7e792600-70ae-11e9-8243-4db8d8ac5dc1.png)
![image](https://user-images.githubusercontent.com/33888917/57266452-8cc74200-70ae-11e9-81f8-211aac677460.png)

Thanks. I love it.

**Comment by agkozak** [comment]
I'm glad it helped!

As to your VS Code problem: it looks as if you're using Cygwin's `bash.exe` as your integrated shell and then launching `zsh.exe` from it, probably from the `.bashrc` -- does that sound correct? At any rate, the problem occurs in `bash`, not `zsh`, so you'll have to look at `.bashrc` (possibly other places, too) for the cause. My guess it that you've got some sort of condition where there's a variable on one side of the `==` that hasn't been set to any value, e.g.

    if [ "$variable" == 12 ]; then
      echo 'The variable is 12'
    fi

If you haven't set `$variable` to any value, then you'll get the error message

    bash: [: ==: unary operator expected

**Comment by WayneChang65** [comment]
Thanks. You are right. _T was set by a windows batch file when I use mouse right-click to run mintty.

![image](https://user-images.githubusercontent.com/33888917/57270770-462e1380-70bf-11e9-99b7-81dbb2fe3304.png)

![image](https://user-images.githubusercontent.com/33888917/57270829-7fff1a00-70bf-11e9-955b-6b94aab28b7a.png)


But _T was not set by VSCode terminal and raise the exception.
I just add
` if [ ! -z "${_T}" ] `
to check the variable _T is set or not and solve it.
Thanks. You're really a Shell script expert.  That's really impressive !! 

![image](https://user-images.githubusercontent.com/33888917/57270114-96f03d00-70bc-11e9-8a8f-a1be0aff9975.png)

![image](https://user-images.githubusercontent.com/33888917/57270121-a1123b80-70bc-11e9-81c5-678dc619d1c8.png)
