### ISSUE TITLE
Option to remove space before prompt character?

### ISSUE THREAD

**Issue by bashwing** [agkozak/agkozak-zsh-prompt#23]
Would it be possible for an option to be added to remove the space before the prompt character, for single-line prompts? For instance, with options
```
export AGKOZAK_MULTILINE=0
export AGKOZAK_PROMPT_CHAR=( \> \# : )
```
I get
```
~/gits/agkozak-zsh-prompt > ls -l
```
I would instead like it to look like:
```
~/gits/agkozak-zsh-prompt> ls -l
```
I realise that this is possible using advanced customisation, and that's what I will look at doing right now, but for maintainability it would be really convenient if there was a simple toggle for this - rather than having to recreate the entire prompt string just to remove a single space.

Is this something you'd be willing to consider?

**Comment by agkozak** [comment]
Give me a day or two and I'll address this. Thanks so much for the suggestion!

**Comment by agkozak** [comment]
OK. On the `develop` branch I've added a variable for you. If you set `AGKOZAK_PRE_PROMPT_CHAR=''`, it will make the space disappear. Alternatively, you could set it to any character or combination of characters.

Let me know if that works for you. I may decided to rename `$AGKOZAK_PRE_PROMPT_CHAR` -- it was the first name I thought of. I'll let you know if I change it. I'll probably release this feature on the master branch along with another feature that I'm still testing out -- expect a new release within a couple of weeks.

**Comment by bashwing** [comment]
Perfect, works great! Thanks for the prompt response!

**Comment by agkozak** [comment]
OK. This featured is now on the `master` branch as part of release `v3.4.0`. Thanks again for your contribution.
