### ISSUE TITLE
Show execution time above a given threshold

### ISSUE THREAD

**Issue by woutgg** [agkozak/agkozak-zsh-prompt#25]
First of all thanks for the nice prompt!

I'm currently trying it out as an alternative to the pure prompt and what I'd like to be able to add is a way to have command execution time shown whenever it takes longer than a configured threshold.

**Comment by agkozak** [comment]
Go to the directory where you've installed agkozak-zsh-prompt and run

    git pull
    git checkout cmd-exec

See if you like what I've done. The current threshold is 5 seconds; you can specify your own threshold using the variable `AGKOZAK_CMD_EXEC_TIME`, or turn off the display entirely with `AGKOZAK_CMD_EXEC_TIME=0`. You'll also get the chance to try out the latest version of the prompt, which I'll be releasing soon; it's a little bit faster here and there.

This seems to be a popular feature of the `pure` prompt, so I like the idea of including it. Out of curiosity: how do you find it most useful?

**Comment by agkozak** [comment]
I'm making a few improvements (I hope!). I've changed the color of the indicator from magenta to 'default' so as to make it less intrusive. I also removed the preceding ellipsis -- it took up too much room, I think.

**Comment by agkozak** [comment]
You can set the color of the command execution time thus:

    AGKOZAK_COLORS_CMD_EXEC_TIME=magenta

or

    AGKOZAK_COLORS_CMD_EXEC_TIME=236

**Comment by woutgg** [comment]
> This seems to be a popular feature of the `pure` prompt, so I like the idea of including it. Out of curiosity: how do you find it most useful?

Wow thanks for adding this so quickly! I'll give it a spin tomorrow and let you know what I think.

As for your question (assuming you were asking what I use it for), these are the two major 'modes' of use that spring to mind:
- The first is whenever I'd otherwise use `time` (e.g. checking script performance, or estimating required total time of repeated operations), and this saves me the distraction of prefixing the command.
- The second are those cases when I wasn't curious about run time beforehand but it appears useful afterwards, for instance when a long running operation was interrupted while I was away, this can sometimes be very informative.

**Comment by agkozak** [comment]
> * The first is whenever I'd otherwise use `time` (e.g. checking script performance, or estimating required total time of repeated operations), and this saves me the distraction of prefixing the command.
> 
> * The second are those cases when I wasn't curious about run time beforehand but it appears useful afterwards, for instance when a long running operation was interrupted while I was away, this can sometimes be very informative.

Works for me! `zsh` actually has a builtin function like that: if you set `REPORTTIME` to a threshold in seconds, the shell will basically run a `time`-like assessment when the execution time of any command exceeds that threshold. But it's not as pretty as what we've just added to the prompt. :)

**Comment by woutgg** [comment]
Ok I've tried it now and it works really nicely. I think your color update to make it less obtrusive is a good one.

There is however one extra feature that will make it more useful, namely pretty printing the time. For anything over ~2 minutes this improves readability a lot. The pure prompt has a simple conversion function for this ([here](https://github.com/sindresorhus/pure/blob/master/pure.zsh#L30)). Since this will potentially generate output with multiple spaces, maybe a configurable prefix+suffix would be handy to add as well?

(BTW, I'm using antibody and the branch switch did not work outright since the repo was configured differently. After I changed it like [described here on SO](https://stackoverflow.com/a/46081117) it worked fine.)

**Comment by woutgg** [comment]
> Works for me! `zsh` actually has a builtin function like that: if you set `REPORTTIME` to a threshold in seconds, the shell will basically run a `time`-like assessment when the execution time of any command exceeds that threshold. But it's not as pretty as what we've just added to the prompt. :)

Oh I didn't know that one. This prompt addition is definitely more practical and pretty though!

**Comment by agkozak** [comment]
@woutgg You're on a roll! Thanks for the suggestions.

I've made `psvar[9]` the pretty-printed string for now; I may or may not keep the raw number of seconds in `psvar[8]` just in case someone wants to use them in a custom prompt. I'll think about it for a few days.

I've also added an array, `AGKOZAK_CMD_EXEC_CHARS`, that can hold characters to prepend and append to the time string; for example

    AGKOZAK_CMD_EXEC_CHARS=( '<' '>' )

will surround the string with angular brackets.  `AGKOZAK_CMD_EXEC_CHARS=( '' ':' )` would append a colon to the string.

I haven't played around with antibody. I'll take a look at it and include instructions for its use with the prompt in the `README.md`.

**Comment by agkozak** [comment]
I've merged this branch back into my `develop` branch, but I'll leave the `cmd-exec` branch (which is presumably stable) around until I release the new version of the prompt.

**Comment by agkozak** [comment]
I've changed the name of that array to `AGKOZAK_CMD_EXEC_TIME_CHARS` -- it's long, but I'll probably be glad for the consistency someday.

**Comment by woutgg** [comment]
Perfect, thank you! I think with these configuration options it makes for a very nice extra feature.

If you run out of `psvar`s (I'm not really familiar with zsh scripting, but it's limited to 9 right?), maybe you could introduce another setting to have either the raw exec time or the human redable version - but I'm not sure that's a very elegant approach.

> I haven't played around with antibody. I'll take a look at it and include instructions for its use with the prompt in the README.md.

Except for the command name it's identical to antigen (at least in the pure prompt docs). The git branch thing I mentioned is only required to switch to a dev version.

> I've changed the name of that array to `AGKOZAK_CMD_EXEC_TIME_CHARS` -- it's long, but I'll probably be glad for the consistency someday.

Ah yes, the everlasting dilemma between practical names and 'good' names. ;)

Thanks again for your work! Looking forward to using the shiny new prompt.

**Comment by agkozak** [comment]
v3.6.0 of the prompt is now available on the `master` branch of the repo, so you can switch over to that. Thanks again for the great suggestions.

Oh, and you may be amused to learn that there are at least 99999 `psvar` elements available, even as far back as ZSH v4.3.11! So I can afford to be generous with these things.

**Comment by woutgg** [comment]
> v3.6.0 of the prompt is now available on the `master` branch of the repo, so you can switch over to that. Thanks again for the great suggestions.
> 
Great! Thank you for your work and the quick addition.

> Oh, and you may be amused to learn that there are at least 99999 `psvar` elements available, even as far back as ZSH v4.3.11! So I can afford to be generous with these things.

Aha I see, that is good to know next time I wander into the world of zsh scripting myself again.
