### ISSUE TITLE
Removing exit status does not work 

### ISSUE THREAD

**Issue by POTATOES-BoilEm-MashEm-StickEm-inAStew** [agkozak/agkozak-zsh-prompt#30]
Hi I love your prompt thanks so much for great documentation!

Unfortunately when i add in 
`AGKOZAK_CMD_EXEC_TIME=0` to disable the status prompt (i.e 127) the exit status still shows! I want to remove the exit status because I do not understand what a 127 or 130 means. I do not want to learn those numbers. It's a hassle.

# Steps I did to reproduce it

## Action
> type in q in the terminal which is in invalid command is not bound by a program

## Expected result
next prompt is shown:
`MYHOSTNAME ~`
thus no exit status is shown

## Actual result
`zsh: command not found: q`
next prompt shows up with the exit status

`(127) MYHOSTNAME ~`

## zshrc file

```sh
source ~/.config/antigen/antigen.zsh
antigen bundle agkozak/agkozak-zsh-prompt
AGKOZAK_CMD_EXEC_TIME=0
antigen apply
```

What can I do to remove the exit status?
Thanks!

**Comment by agkozak** [comment]
`AGKOZAK_CMD_EXEC_TIME=0` doesn't disable the exit status display; it disables execution time display.

There isn't, at present, a simple setting that will suppress display of the exit status (I haven't had anyone request that before), but luckily it can be easily managed. If that's the only customization you're doing, you can just set `AGKOZAK_CUSTOM_PROMPT` thus in your `.zshrc`:
```sh
# Command execution time
AGKOZAK_CUSTOM_PROMPT='%(9V.%9v .)'
# Username and hostname
AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{green})%n%1v%(!.%b%s.%f%b) '
# Path
AGKOZAK_CUSTOM_PROMPT+=$'%B%F{blue}%2v%f%b\n'
# Prompt character
AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '
```

Let me know if that works.

I will consider adding a simple way of disabling exit status display in an upcoming release of the prompt. Thank you so much for helping to make it better.

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
Oh my bad! Thank you for your kind answer much appreciated.
The script you show works. That's all I need for now.

Good work!
