### ISSUE TITLE
[Question] Can an additional command be executed to be shown on the shell?

### ISSUE THREAD

**Issue by 0xsentinel** [agkozak/agkozak-zsh-prompt#31]
Hi,

It is possible to execute an selfade custom command (e.g curl icanhazip.com)?
For example I wish to show my ip address on the prompt.

I know that it is possible to edit the .zsh source code and add it yourself but perhaps you know a faster way by setting a custom variable in my ~/.zshrc settings. 
I find it hard to solve this problem myself because I do not understand the docs for example at the section
`AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{green})%n%1v%(!.%b%s.%f%b) '`
I know you have somewhere written that you want to rewrite it to be easier read.

I have read all documentation but still I am confused.

Thanks!

**Comment by agkozak** [comment]
The ideal way of doing this is not to use an external command at all, but rather just an environment variable -- that's extremely fast. If you're using SSH to connect to servers and you only need to know the IP addresses of the servers you're connected to (as opposed to your local machine), you can use a small function to parse `SSH_CONNECTION`:

```sh
_0xsentinel_ip() {
	[[ -z $* ]] && return
	shift; shift
	print "[IP: $1] "
}
```

This function can parse the environment variable `SSH_CONNECTION` and find the third element in it, which contains the server IP address. Then you can just add a line to the default prompts:

```sh
# IP
AGKOZAK_CUSTOM_PROMPT='$(_0xsentinel_ip ${=SSH_CONNECTION})'
# Exit status
AGKOZAK_CUSTOM_PROMPT+='%(?..%B%F{red}(%?%)%f%b )'
# Command execution time
AGKOZAK_CUSTOM_PROMPT+='%(9V.%9v .)'
# Username and hostname
AGKOZAK_CUSTOM_PROMPT+='%(!.%S%B.%B%F{green})%n%1v%(!.%b%s.%f%b) '
# Path
AGKOZAK_CUSTOM_PROMPT+=$'%B%F{blue}%2v%f%b\n'
# Prompt character
AGKOZAK_CUSTOM_PROMPT+='%(4V.:.%#) '

# Git status
AGKOZAK_CUSTOM_RPROMPT='%(3V.%F{yellow}%3v%f.)'
```
If I were to make this feature a permanent option in the prompt, the one difference to how I implement it would be that the server IP would always be calculated and available in a special prompt variable -- that way not even command substitution (`$( ... )`) would be necessary -- that can slow things down just slightly.

If you really need to know your IP address even when you're just using a machine locally, that can be done, too, although it's inherently more complex and slow. We'd have to run a test to see what OS you're using and pick a command that will be sure to exist on that system.

**Comment by 0xsentinel** [comment]
Thank for your quick answer! It's actually very simple to implement to show your public IP. 
add to `~/.zshrc`

```sh
IP=$(curl --tlsv1.3 --ssl -s https://icanhazip.com)
AGKOZAK_CUSTOM_RPROMPT='$IP'
```

That fixes my issue. There are no problems of the prompt being slow.
