### ISSUE TITLE
Prompt overwrites last displayed line when catting file without trailing newline

### ISSUE THREAD

**Issue by woutgg** [agkozak/agkozak-zsh-prompt#46]
When using `cat` to display a file without trailing newline, the last line can (sometimes) be seen very briefly and is then overwritten by the (left-)prompt.

Perhaps a non-empty line could be detected in which case the prompt either does not clear the line, or emits a newline first.

**Comment by agkozak** [comment]
Have you tried setting

    AGKOZAK_BLANK_LINES=1

in your `.zshrc`? That's a simple solution.

**Comment by woutgg** [comment]
Ah, I missed that one. It's not exactly what I had in mind but it might work just fine; I'll try it for a while. Thank you!

**Comment by edemaine** [comment]
I'd personally prefer not to add a blank line every time, only when necessary (with some kind of "(no EOL)" marker). But I'm not sure it's possible to detect beginning-of-line — is it?

**Comment by woutgg** [comment]
That would be my preference as well.
I thought at first that it would be possible to detect/request cursor position, but on second thought I'm not sure if it's feasible to do so in the context of a shell prompt (as far as I know you'd have to read 'keyboard input' emitted by an ANSI command). I'm far from an expert at this though.

**Comment by agkozak** [comment]
@woutgg @edemaine Could you try adding

    setopt PROMPT_CR

to the end of your `.zshrc` and see if that produces the desired effect?

**Comment by woutgg** [comment]
That works very nicely, especially since it highlights the fact that the output is unterminated.
I wasn't aware of this option. Interestingly it appears to be on by default, so it is probably switched off somewhere in a plugin.
Thank you!

**Comment by agkozak** [comment]
> Interestingly it appears to be on by default, so it is probably switched off somewhere in a plugin.

@woutgg You're absolutely right, and it's my fault that it's getting turned off. I'll get this fixed in the next couple of days, all right? Thanks for your patience, and thanks for giving that temporary fix a try.

**Comment by agkozak** [comment]
Release [v3.11.4](https://github.com/agkozak/agkozak-zsh-prompt/releases/tag/v3.11.4) contains a fix for the reported behavior. Just go ahead and update the `master` branch, and thanks, everyone, for helping to make the prompt better.

**Comment by edemaine** [comment]
Awesome, thanks both for finding the option and fixing it!

For anyone running into this, I also found it nice to be able to customize the string (default is `%` in standout font, or equivalently `%S%%%s`):

```sh
export PROMPT_EOL_MARK="%S[NO EOL]%s"
```

Sadly it doesn't seem to be possible to put this on the line after the unterminated line (as far as I can tell). Oh well, good enough!

**Comment by woutgg** [comment]
Great, thank you @agkozak for your efforts on this and the awesome prompt in general!
